// // tests/report-download.spec.js
// import { test, expect } from '@playwright/test';
// import path from 'path';
// import { selectFromSearchableDropdown } from '../../../utils/dropdownHelper.js';
// import { selectDateRange } from '../../../utils/dateRangeHelper.js';

// test.use({
//       //storageState: 'storageState.json',
//   launchOptions: {
//     slowMo: 300,
//   },
// });

// test.describe.serial('Sanity - Report Download', () => {
//   test.setTimeout(120_000);

//   test('Download Overall Summary View Report (Excel)', async ({ page }) => {

//     // // ---------------- LOGIN ----------------
//       await page.goto('https://crmqa2.pooraa.net/login');

//     // await page.getByRole('textbox', { name: 'Enter your email' })
//     //   .fill('crm@busy.in');

//     // await page.getByRole('button', { name: 'Continue', exact: true }).click();

//     // await page.locator('#_r_4_').fill('6');
//     // await page.locator('#_r_5_').fill('5');
//     // await page.locator('#_r_6_').fill('4');
//     // await page.locator('#_r_7_').fill('3');
//     // await page.locator('#_r_8_').fill('2');
//     // await page.locator('#_r_9_').fill('1');

//     // // ---------- NAVIGATE TO REPORT ----------
//     // await page.getByRole('button', { name: 'Busy Pvt. Ltd.' }).click();
//     await page.getByLabel('Main Navigation')
//       .getByRole('menuitem', { name: 'Report' })
//       .click();

//     await page.getByRole('row', { name: /Overall Summary View Report/i })
//       .getByLabel('Download Report')
//       .click();

//     // ---------------- FILTERS ----------------
//     await selectFromSearchableDropdown(
//       page,
//       'Assigned To',
//       'super',
//       'CRM SUPER ADMIN'
//     );

//     await selectFromSearchableDropdown(
//       page,
//       'Partner Name',
//       '3m',
//       '3M Overseas'
//     );

//     await selectFromSearchableDropdown(
//       page,
//       'Generated By',
//       'bipl',
//       'BIPL'
//     );

//     // ✅ Date Range (NOW STABLE)
//     await selectDateRange(page, 1, 7);

//     // ---------------- DOWNLOAD ----------------
//     console.log('⏳ Waiting for report generation (20s)...');
//     await page.waitForTimeout(20_000);

//   const filtersDialog = page.getByRole('dialog', { name: /advance filters/i });

// // Wait for dialog to be ready
// await expect(filtersDialog).toBeVisible();

// // Click the Excel (last icon button in footer)
// await filtersDialog
//   .locator('button')
//   .filter({ has: page.locator('svg') })
//   .last()
//   .click();

//   // Wait until at least one completed Overall Summary report is visible
// const completedOverallSummaryRows = page
//   .getByRole('row')
//   .filter({ hasText: 'Overall Summary' })
//   .filter({ hasText: 'Completed' });

// await expect(
//   completedOverallSummaryRows.first()
// ).toBeVisible({ timeout: 60_000 });


// // Pick latest report (top row)
// const latestOverallSummaryRow = page
//   .getByRole('row')
//   .filter({ hasText: 'Overall Summary' })
//   .filter({ hasText: 'Completed' })
//   .filter({ hasText: 'XLSX' })
//   .first();

// await expect(latestOverallSummaryRow).toBeVisible();

// const downloadButton = latestOverallSummaryRow.getByRole('button', {
//   name: /^download$/i,
// });

// await expect(downloadButton).toBeEnabled();
// await downloadButton.scrollIntoViewIfNeeded();

// const [download] = await Promise.all([
//   page.waitForEvent('download'),
//   downloadButton.click(),
// ]);

// const filePath = path.join(
//   process.cwd(),
//   'downloads',
//   await download.suggestedFilename()
// );

// await download.saveAs(filePath);
// expect(download.suggestedFilename()).toMatch(/\.xlsx$/);


//   });
// });






// tests/report-download.spec.js
import { test, expect } from '@playwright/test';
import path from 'path';
import { selectFromSearchableDropdown } from '../../../utils/dropdownHelper.js';
import { selectDateRange } from '../../../utils/dateRangeHelper.js';

test.use({
      //storageState: 'storageState.json',
  launchOptions: {
    slowMo: 300,
  },
});

test.describe.serial('Sanity - Report Download', () => {
  test.setTimeout(120_000);

  test('Download Overall Summary View Report (Excel)', async ({ page }) => {

    // // ---------------- LOGIN ----------------
      await page.goto('https://crmqa2.pooraa.net/login');

    await page.getByRole('textbox', { name: 'Enter your email' })
      .fill('crm@busy.in');

    await page.getByRole('button', { name: 'Continue', exact: true }).click();

    await page.locator('#_r_4_').fill('6');
    await page.locator('#_r_5_').fill('5');
    await page.locator('#_r_6_').fill('4');
    await page.locator('#_r_7_').fill('3');
    await page.locator('#_r_8_').fill('2');
    await page.locator('#_r_9_').fill('1');

    // // ---------- NAVIGATE TO REPORT ----------
    // await page.getByRole('button', { name: 'Busy Pvt. Ltd.' }).click();
    await page.getByLabel('Main Navigation')
      .getByRole('menuitem', { name: 'Report' })
      .click();

    await page.getByRole('row', { name: /Overall Summary View Report/i })
      .getByLabel('Download Report')
      .click();

    // ---------------- FILTERS ----------------
    await selectFromSearchableDropdown(
      page,
      'Assigned To',
      'super',
      'CRM SUPER ADMIN'
    );

    await selectFromSearchableDropdown(
      page,
      'Partner Name',
      '3m',
      '3M Overseas'
    );

    await selectFromSearchableDropdown(
      page,
      'Generated By',
      'bipl',
      'BIPL'
    );

    // ✅ Date Range (NOW STABLE)
    await selectDateRange(page, 1, 7);

    // ---------------- DOWNLOAD ----------------
    console.log('⏳ Waiting for report generation (20s)...');
    await page.waitForTimeout(20_000);

  const filtersDialog = page.getByRole('dialog', { name: /advance filters/i });

// Wait for dialog to be ready
await expect(filtersDialog).toBeVisible();

// Click the Excel (last icon button in footer)
await filtersDialog
  .locator('button')
  .filter({ has: page.locator('svg') })
  .last()
  .click();

  // Wait until at least one completed Overall Summary report is visible
const completedOverallSummaryRows = page
  .getByRole('row')
  .filter({ hasText: 'Overall Summary' })
  .filter({ hasText: 'Completed' });

await expect(
  completedOverallSummaryRows.first()
).toBeVisible({ timeout: 60_000 });


// Pick latest report (top row)
const latestOverallSummaryRow = page
  .getByRole('row')
  .filter({ hasText: 'Overall Summary' })
  .filter({ hasText: 'Completed' })
  .filter({ hasText: 'XLSX' })
  .first();

await expect(latestOverallSummaryRow).toBeVisible();

const downloadButton = latestOverallSummaryRow.getByRole('button', {
  name: /^download$/i,
});

await expect(downloadButton).toBeEnabled();
await downloadButton.scrollIntoViewIfNeeded();

const [download] = await Promise.all([
  page.waitForEvent('download'),
  downloadButton.click(),
]);

const filePath = path.join(
  process.cwd(),
  'downloads',
  await download.suggestedFilename()
);

await download.saveAs(filePath);
expect(download.suggestedFilename()).toMatch(/\.xlsx$/);


  });
});

